import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AppHeader } from '../components/AppHeader'
import { useSuggestions } from '../features/suggestions/hooks/useSuggestions'
import type { SuggestionCategory, SuggestionInput, SuggestionSort, SuggestionStatus } from '../features/suggestions/types'
import type { Profile } from '../types/profile'

const categories: Array<[SuggestionCategory, string]> = [['gameplay','Gameplay'],['characters','Characters'],['verses','Verses'],['ui-ux','UI / UX'],['balance','Balance'],['bugs','Bugs'],['other','Other']]
const statuses: Array<[SuggestionStatus, string]> = [['submitted','Submitted'],['under_review','Under Review'],['planned','Planned'],['implemented','Implemented'],['declined','Declined']]
type CommunityTab = 'guide' | 'faq' | 'suggestions'
interface Props { currentUserId: string; profile: Profile; avatarUrl: string | null }

const flow = [
  ['01','Matchmaking','Join the online queue and enter a server-authoritative match when an opponent is found. Refreshing or briefly disconnecting does not automatically forfeit.'],
  ['02','RPS Initiative','Both players secretly choose Rock, Paper, or Scissors. The winner receives initial draft priority; a draw means choosing again.'],
  ['03','Secret OC Selection','See each other’s possible equipped OC Family, then secretly select one OC. Its match stats are snapshotted.'],
  ['04','Draft / Auction','Draft five canon fighters from a shared pool of ten using a $20 starting balance and priority-based bidding.'],
  ['05','OC Preparation','Keep all five canon fighters and your OC as reserve, or sacrifice one same-verse fighter for a temporary OC OVR boost.'],
  ['06','Battle','Secretly lock one unused fighter per round. Fighters reveal together and the server resolves the winner.'],
  ['07','Result','First to three round wins takes the match. A match can last no more than five rounds.'],
  ['08','OC Progression','Eligible gameplay awards progression points that can improve OVR or Battle Power within the OC’s caps.'],
]

const faqs = [
  ['Battle','Why did a fighter with lower Battle Power win?','OVR is the primary battle stat. Battle Power is only used when both fighters have the same OVR.'],
  ['Battle','Can I use a fighter more than once?','No. Once a fighter is used in a round, it cannot be selected again during that match.'],
  ['Battle','What happens if both fighters have the same OVR and Power?','The round is a draw. Neither player scores, but both fighters are still consumed.'],
  ['OCs','Do I have to use my OC?','No. Your OC is an optional reserve fighter and can only be played once.'],
  ['OCs','Can my OC reach 99 OVR permanently?','No. Permanent OVR follows the OC’s archetype cap. Sacrifice may temporarily raise match OVR to a maximum of 99.'],
  ['OCs','Does sacrificing permanently delete a fighter?','No. That drafted fighter is unavailable only for the current match.'],
  ['OCs','Does sacrifice increase Battle Power?','No. Sacrifice only raises temporary match OVR.'],
  ['OCs','Why can’t I sacrifice a fighter?','The drafted fighter must belong to the same verse as your selected OC.'],
  ['OCs','How many OCs can I own and equip?','You may own multiple OCs, but only three active OCs can be equipped in your OC Family.'],
  ['Draft','What determines draft priority?','RPS establishes initial priority. Later priority favors the higher remaining balance, with alternating tie priority when balances match.'],
  ['Draft','What happens if I Pass or Fold?','Pass gives the current fighter to your opponent for $0. During bidding, Fold gives the fighter to the current leading bidder at the current bid.'],
  ['Matches','Can I leave a match?','Before battle, Cancel Match abandons the match without a winner. During battle, Forfeit Match awards the opponent the win.'],
]

export function Suggestions({ currentUserId, profile, avatarUrl }: Props) {
  const [tab, setTab] = useState<CommunityTab>('guide')
  return <main className="suggestions-page community-page"><AppHeader active="suggestions" username={profile.username} avatarUrl={avatarUrl}/><section className="suggestions-content community-content">
    <header className="community-hero"><div><p className="eyebrow">Community</p><h1>Game Guide</h1><p>Learn how Anime Arena works, review common questions, and share ideas for improving the game.</p></div><div className="community-guide-art" aria-hidden="true"><span>✦</span><div><b>⌑</b><i>⚔</i></div><span>✦</span></div></header>
    <div className="community-tabs" role="tablist" aria-label="Community sections">{([['guide','▣','How to Play'],['faq','?','FAQ'],['suggestions','♧','Suggestions']] as Array<[CommunityTab,string,string]>).map(([key,icon,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}><i aria-hidden="true">{icon}</i>{label}</button>)}</div>
    {tab==='guide'?<HowToPlay/>:tab==='faq'?<Faq/>:<SuggestionsBoard currentUserId={currentUserId} profile={profile}/>} 
  </section></main>
}

function HowToPlay(){const steps=[['Find an opponent','Join matchmaking and get matched.'],['Win RPS for first priority','Rock, Paper, Scissors determines draft priority.'],['Draft a team of five','Build your team in the auction draft.'],['Prepare your OC','Keep as reserve or sacrifice for a boost.'],['Secretly choose fighters','Lock your picks each round and battle.'],['First to three wins','Best of up to five rounds. Claim victory.']];return <div className="community-section" role="tabpanel">
  <section className="quick-start"><div><p className="eyebrow">ϟ Quick Start</p><h2>Your match in<br/>six moves</h2><p>A quick overview of the full match flow.</p></div><ol>{steps.map(([title,text],index)=><li key={title}><b>{index+1}</b><span><strong>{title}</strong><small>{text}</small></span></li>)}</ol></section>
  <section><div className="community-heading"><p className="eyebrow">Full Match</p><h2>How a match works</h2></div><div className="game-flow-grid">{flow.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="draft-guide"><div className="community-heading"><p className="eyebrow">Draft Guide</p><h2>Build your team strategically</h2></div><div className="guide-card-grid"><article><h3>Shared Pool</h3><p>Ten canon fighters enter the draft. Each player finishes with exactly five and starts with $20.</p><ul><li>Higher remaining balance gets later priority.</li><li>Tied balances use alternating tie priority.</li><li>Remaining cards safely fill the other team after one roster reaches five.</li></ul></article><article><h3>Priority Actions</h3><dl><dt>Pass</dt><dd>Your opponent receives the fighter for $0.</dd><dt>Bid</dt><dd>Open bidding using your available balance.</dd><dt>Raise</dt><dd>Increase the current bid.</dd><dt>Fold</dt><dd>The leading bidder receives the fighter at the current bid.</dd></dl></article></div></section>
  <BattleGuide/><OcGuide/>
  <section className="leaderboard-guide"><div><p className="eyebrow">Rankings</p><h2>Leaderboards</h2></div><div><article><h3>Players</h3><p>Ranked through PvP wins and losses.</p></article><article><h3>Individual OCs</h3><p>Compare OVR, Battle Power, or Growth.</p></article><article><h3>OC Families</h3><p>Equip exactly three active OCs to rank Family OVR, Power, and Growth.</p></article></div></section>
  <section className="community-cta"><p className="eyebrow">Ready to Play?</p><h2>Enter the arena</h2><div><Link className="button button-primary" to="/">Find a Match</Link><Link className="button button-secondary" to="/ocs">Create / Manage OCs</Link></div></section>
  </div>}

function BattleGuide(){return <section className="battle-guide"><div className="community-heading"><p className="eyebrow">Critical Rule</p><h2>How battles are decided</h2></div><div className="battle-rule-layout"><article className="battle-rule-card"><ol><li><strong>Higher OVR wins.</strong></li><li>If OVR ties, higher Battle Power wins.</li><li>If both stats tie, the round is a draw.</li><li>Both fighters are consumed, including on a draw.</li><li>First to three round wins wins the match.</li><li>Maximum five rounds.</li></ol></article><article className="battle-example"><div><span>Fighter A</span><b>90 OVR</b><small>9,500 Power</small></div><i>VS</i><div className="winner"><span>Fighter B</span><b>91 OVR</b><small>6,000 Power</small></div><p><strong>Fighter B wins.</strong> 91 OVR beats 90 OVR regardless of Power.</p></article></div><div className="stat-explainer"><article><h3>OVR</h3><p>The primary combat rating. Higher OVR always beats lower OVR.</p></article><article><h3>Battle Power</h3><p>Used only as the tie-breaker when both fighters have equal OVR.</p></article><article><h3>Secret Selection</h3><p>Both players lock an unused fighter in secret. They reveal simultaneously and the server resolves the round.</p></article></div></section>}

function OcGuide(){return <section className="oc-guide"><div className="community-heading"><p className="eyebrow">Your OC</p><h2>Build your own fighter</h2><p>Choose a verse, discover a randomized 50–60 starting OVR, and begin at 5,000 Battle Power. Equip up to three OCs; one may be secretly selected per match.</p></div><h3>Starting archetypes</h3><div className="guide-table archetypes">{[['50–52','High Potential','92','10,000'],['53–55','Growth-Focused','93','9,500'],['56–58','Balanced','94','9,000'],['59–60','Prodigy','95','8,500']].map(row=><article key={row[0]}><b>{row[0]} OVR</b><strong>{row[1]}</strong><span>OVR Cap {row[2]}</span><span>Power Cap {row[3]}</span></article>)}</div><p className="guide-note">Lower starters can develop more Battle Power; higher starters reach a slightly higher permanent OVR.</p>
  <div className="guide-card-grid"><article><h3>Progression</h3><p>Spend eligible progression points on OVR or Power, respecting individual caps.</p><ul><li>OVR 50–69: 1 point</li><li>70–79: 2 points</li><li>80–89: 3 points</li><li>90+: 4 points</li><li>1 point adds 50 Power</li></ul></article><article><h3>Secret OC Selection</h3><p>Your opponent sees your possible equipped family, but not which OC you choose. Match stats are snapshotted, creating room to bluff during the draft.</p><p>Portraits are cosmetic and never affect stats.</p></article></div>
  <h3>Preparation and sacrifice</h3><div className="guide-card-grid preparation-choices"><article><h3>Keep as Reserve</h3><p>Keep five canon fighters and your normal-stat OC reserve.</p></article><article><h3>Sacrifice a Fighter</h3><p>Trade one same-verse fighter for a temporary OC OVR boost.</p></article></div><div className="guide-table tiers">{[['D','50–64','+1'],['C','65–74','+2'],['B','75–84','+3'],['A','85–94','+4'],['S','95–98','+5'],['LEGEND','99','+6']].map(row=><article key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><strong>{row[2]}</strong></article>)}</div><div className="rule-callout sacrifice-summary"><strong>Key rules</strong><span>Maximum 99 temporary OVR · no Power or permanent stat increase · one OC play · maximum five rounds.</span></div>
  </section>}

function Faq(){const [open,setOpen]=useState<number|null>(0);const [search,setSearch]=useState('');const visible=faqs.map((item,index)=>({item,index})).filter(({item})=>!search.trim()||`${item[0]} ${item[1]} ${item[2]}`.toLowerCase().includes(search.toLowerCase()));return <div className="community-section faq-section" role="tabpanel"><div className="community-heading"><p className="eyebrow">Questions Answered</p><h2>Frequently Asked Questions</h2></div><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search questions..." aria-label="Search frequently asked questions"/><div>{visible.map(({item,index})=><article key={item[1]}><button aria-expanded={open===index} aria-controls={`faq-${index}`} onClick={()=>setOpen(open===index?null:index)}><span><small>{item[0]}</small>{item[1]}</span><i>{open===index?'−':'+'}</i></button>{open===index&&<p id={`faq-${index}`}>{item[2]}</p>}</article>)}</div></div>}

function SuggestionsBoard({currentUserId,profile}:{currentUserId:string;profile:Profile}){const board=useSuggestions(currentUserId);const [formOpen,setFormOpen]=useState(false);const [search,setSearch]=useState('');const [category,setCategory]=useState<'all'|SuggestionCategory>('all');const [sort,setSort]=useState<SuggestionSort>('upvoted');const [form,setForm]=useState<SuggestionInput>({title:'',description:'',category:'gameplay'});const [formError,setFormError]=useState<string|null>(null);const [submitting,setSubmitting]=useState(false)
  const visible=useMemo(()=>{const query=search.trim().toLowerCase();return board.suggestions.filter(item=>(category==='all'||item.category===category)&&(!query||item.title.toLowerCase().includes(query)||item.description.toLowerCase().includes(query))).toSorted((a,b)=>sort==='upvoted'?b.vote_count-a.vote_count||Date.parse(b.created_at)-Date.parse(a.created_at):sort==='newest'?Date.parse(b.created_at)-Date.parse(a.created_at):Date.parse(a.created_at)-Date.parse(b.created_at))},[board.suggestions,category,search,sort])
  const submit=async()=>{const input={...form,title:form.title.trim(),description:form.description.trim()};if(input.title.length<3||input.title.length>120)return setFormError('Title must be between 3 and 120 characters.');if(input.description.length<10||input.description.length>2000)return setFormError('Description must be between 10 and 2,000 characters.');setSubmitting(true);setFormError(null);try{await board.submit(input);setForm({title:'',description:'',category:'gameplay'});setFormOpen(false)}catch{setFormError('Unable to submit your suggestion.')}finally{setSubmitting(false)}}
  return <div className="community-section suggestions-board" role="tabpanel"><header className="suggestions-hero"><div><p className="eyebrow">Share Your Ideas</p><h2>Help shape Anime Arena</h2><p>Suggest characters, verses, balance changes, game modes, UI improvements, and new features.</p></div><button className="button button-primary" onClick={()=>setFormOpen(true)}>+ Submit Suggestion</button></header>{board.message&&<p className="suggestions-message" role="status">{board.message}</p>}{formOpen&&<section className="suggestion-form"><div className="suggestion-form-heading"><h2>Submit a Suggestion</h2><button onClick={()=>setFormOpen(false)} aria-label="Close form">×</button></div><label>Title<input maxLength={120} value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label>Category<select value={form.category} onChange={event=>setForm({...form,category:event.target.value as SuggestionCategory})}>{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Description<textarea maxLength={2000} rows={6} value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label>{formError&&<p className="error-message" role="alert">{formError}</p>}<div className="suggestion-form-actions"><button className="button button-secondary" onClick={()=>setFormOpen(false)}>Cancel</button><button className="button button-primary" disabled={submitting} onClick={()=>void submit()}>{submitting?'Submitting...':'Submit Suggestion'}</button></div></section>}
  <div className="suggestions-filters"><input aria-label="Search suggestions" type="search" placeholder="Search suggestions..." value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Filter by category" value={category} onChange={event=>setCategory(event.target.value as 'all'|SuggestionCategory)}><option value="all">All Categories</option>{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Sort suggestions" value={sort} onChange={event=>setSort(event.target.value as SuggestionSort)}><option value="upvoted">Most Upvoted</option><option value="newest">Newest</option><option value="oldest">Oldest</option></select></div>{board.loading?<div className="catalogue-state"><h2>Loading suggestions...</h2></div>:board.error?<div className="catalogue-state"><h2>Unable to load suggestions.</h2><button className="button button-secondary" onClick={()=>void board.refresh()}>Retry</button></div>:visible.length===0?<div className="catalogue-state"><h2>No suggestions found.</h2><button className="button button-primary" onClick={()=>setFormOpen(true)}>Submit a Suggestion</button></div>:<div className="suggestions-list">{visible.map(item=><article className="suggestion-card" key={item.id}><div className="suggestion-vote"><button className={item.current_user_voted?'voted':''} disabled={board.pendingId===item.id} onClick={()=>void board.toggleVote(item)} aria-label={item.current_user_voted?'Remove upvote':'Upvote suggestion'}>▲</button><strong>{item.vote_count}</strong></div><div className="suggestion-body"><div className="suggestion-meta"><span>{categories.find(([value])=>value===item.category)?.[1]}</span>{profile.is_admin?<select value={item.status} disabled={board.pendingId===item.id} onChange={event=>void board.setStatus(item.id,event.target.value as SuggestionStatus)}>{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<b className={`suggestion-status status-${item.status}`}>{statuses.find(([value])=>value===item.status)?.[1]}</b>}</div><h2>{item.title}</h2><p>{item.description}</p><small>Suggested by {item.author_username} • {new Date(item.created_at).toLocaleDateString()}</small></div></article>)}</div>}</div>}
