import { useEffect, useRef, useState } from 'react'
import type { MatchOcPreparationState } from '../types'
import { OCImage } from '../../ocs/components/OCImage'
import { useGameSounds } from '../../audio/useGameSounds'

interface Props { state:MatchOcPreparationState;pending:boolean;error:string|null;onLock:(decision:'reserve'|'sacrifice',sacrificedId:string|null)=>Promise<void> }

export function OcPreparationScreen({state,pending,error,onLock}:Props){
  const [choice,setChoice]=useState<{decision:'reserve'|'sacrifice';id:string|null}>({decision:'reserve',id:null});const oc=state.yourOC
  const sounds=useGameSounds();const lockSeen=useRef(state.yourLocked)
  useEffect(()=>{if(!lockSeen.current&&state.yourLocked)sounds.playLockIn();lockSeen.current=state.yourLocked},[sounds,state.yourLocked])
  const selectChoice=(next:{decision:'reserve'|'sacrifice';id:string|null})=>{if(choice.decision===next.decision&&choice.id===next.id)return;setChoice(next);sounds.playCardSelect()}
  if(!oc)return <main className="game-page preparation-page"><WaitingState title="No OC Selected" text="Your preparation is complete. Waiting for your opponent..."/></main>
  if(state.yourLocked){const sacrificed=state.eligibleSacrifices.find(card=>card.matchCharacterId===state.yourPreparation?.sacrificedMatchCharacterId);return <main className="game-page preparation-page"><section className="oc-preparation waiting"><p className="eyebrow">OC Preparation Locked</p><h1>{state.yourPreparation?.decision==='sacrifice'?'Absorption Complete':'Reserve Ready'}</h1><OcSummary name={oc.name} verse={oc.verseName} overall={state.yourPreparation?.matchOverall??oc.baseOverall} power={oc.powerScore}/>{sacrificed&&<div className="locked-absorption"><b>Boosted +{sacrificed.sacrificeBoost} OVR</b><span>Absorbed {sacrificed.name} · {sacrificed.tier} Tier</span></div>}<div className="preparation-waiting"><i>⌛</i><strong>{state.opponentLocked?'Opponent locked. Preparing battle...':'Waiting for opponent to lock in...'}</strong></div></section></main>}
  const selectedSacrifice=state.eligibleSacrifices.find(card=>card.matchCharacterId===choice.id)
  return <main className="game-page preparation-page"><section className="oc-preparation"><p className="eyebrow">OC Preparation</p><h1>Choose Your Strategy</h1><OcSummary name={oc.name} verse={oc.verseName} overall={oc.baseOverall} power={oc.powerScore}/>{error&&<p className="online-draft-message" role="alert">{error}</p>}
    <div className="strategy-grid"><button type="button" aria-pressed={choice.decision==='reserve'} className={`strategy-card ${choice.decision==='reserve'?'selected':''}`} onMouseEnter={sounds.playCardHover} onClick={()=>selectChoice({decision:'reserve',id:null})}><span className="strategy-icon">♕</span><small>Recommended</small><h2>Keep as Reserve</h2><p>No sacrifice. All five canon fighters remain available.</p><strong>Your OC stays ready.</strong><div className="reserve-visual"><span/><span/><span/><span/><i>✦</i></div></button>
      <section className={`strategy-card sacrifice ${choice.decision==='sacrifice'?'selected':''}`}><span className="strategy-icon">⚔</span><h2>Sacrifice a Fighter</h2><p>Absorb one same-verse fighter for a temporary OVR boost.</p><strong>One fighter will be unavailable.</strong>{state.eligibleSacrifices.length===0?<div className="no-sacrifice"><b>No same-verse fighters available.</b><span>You can still keep your OC as reserve.</span></div>:<div className="sacrifice-options">{state.eligibleSacrifices.map(card=><button type="button" aria-pressed={choice.id===card.matchCharacterId} key={card.matchCharacterId} className={choice.id===card.matchCharacterId?'selected':''} onMouseEnter={sounds.playCardHover} onClick={()=>selectChoice({decision:'sacrifice',id:card.matchCharacterId})}><span><b>{card.name}</b><small>{card.overall} OVR · {card.tier} Tier</small></span><i>→</i><strong>+{card.sacrificeBoost}<small> OVR</small></strong></button>)}</div>}{selectedSacrifice&&<div className="absorption-result"><span>{selectedSacrifice.name}</span><b>{oc.baseOverall} → {Math.min(99,oc.baseOverall+selectedSacrifice.sacrificeBoost)} OVR</b></div>}</section></div>
    <div className="preparation-warning"><i>!</i><p>Sacrificed fighters cannot be used in battle this match.<br/>This decision cannot be changed.</p></div><button className="button button-primary preparation-lock" disabled={pending||(choice.decision==='sacrifice'&&!choice.id)} onClick={()=>void onLock(choice.decision,choice.id)}>{pending?'Locking...':'Lock Preparation'}</button>
  </section></main>
}
function OcSummary({name,verse,overall,power,imageUrl=null}:{name:string;verse:string;overall:number;power:number;imageUrl?:string|null}){return <div className="oc-preparation-summary"><OCImage src={imageUrl} name={name} className="oc-preparation-portrait" /><span><strong>{name}</strong><small>{verse}</small></span><div><b>{overall} OVR</b><small>{power.toLocaleString()} Power</small></div></div>}
function WaitingState({title,text}:{title:string;text:string}){return <section className="oc-preparation waiting"><p className="eyebrow">OC Preparation</p><h1>{title}</h1><div className="preparation-waiting"><i>⌛</i><strong>{text}</strong></div></section>}
