import { useEffect, useRef, useState } from 'react'
import type { MatchOcPreparationState, OcPreparationDecision } from '../types'
import { OCImage } from '../../ocs/components/OCImage'
import { useGameSounds } from '../../audio/useGameSounds'

interface Props { state: MatchOcPreparationState; pending: boolean; error: string | null; onLock: (decision: 'reserve' | 'absorb' | 'inactive' | 'sacrifice', sacrificedId: string | null) => Promise<void> }
interface Choice { decision: OcPreparationDecision; id: string | null }

export function OcPreparationScreen({ state, pending, error, onLock }: Props) {
  const oc = state.yourOC
  const [choice, setChoice] = useState<Choice>({ decision: oc?.ocType ? 'reserve' : 'none', id: null })
  const sounds = useGameSounds(); const lockSeen = useRef(state.yourLocked)
  useEffect(() => { if (!lockSeen.current && state.yourLocked) sounds.playLockIn(); lockSeen.current = state.yourLocked }, [sounds, state.yourLocked])
  const selectChoice = (next: Choice) => { if (choice.decision === next.decision && choice.id === next.id) return; setChoice(next); sounds.playCardSelect() }
  if (!oc) return <main className="game-page preparation-page"><WaitingState title="No OC Selected" text="Your preparation is complete. Waiting for your opponent..." /></main>
  if (oc.ocType !== 'champion' && oc.ocType !== 'sacrificial') {
    return <main className="game-page preparation-page"><section className="oc-preparation waiting"><p className="eyebrow">OC Preparation</p><h1>OC Type Unavailable</h1><OcSummary name={oc.name} verse={oc.verseName} type={oc.ocType} overall={oc.baseOverall} power={oc.powerScore} imageUrl={oc.imageUrl} /><p className="online-draft-message" role="alert">This match is missing the authoritative OC type snapshot. Start a new match after applying the latest OC Types migration.</p></section></main>
  }
  if (state.yourLocked) {
    const prep = state.yourPreparation; const absorbed = state.eligibleSacrifices.find(card => card.matchCharacterId === prep?.sacrificedMatchCharacterId)
    const title = prep?.decision === 'absorb' ? 'Absorption Complete' : prep?.decision === 'sacrifice' ? 'Team Empowered' : prep?.decision === 'reserve' ? 'Reserve Ready' : 'Support Inactive'
    return <main className="game-page preparation-page"><section className="oc-preparation waiting"><p className="eyebrow">OC Preparation Locked</p><h1>{title}</h1><OcSummary name={oc.name} verse={oc.verseName} type={oc.ocType} overall={prep?.matchOverall ?? oc.baseOverall} power={oc.powerScore} imageUrl={oc.imageUrl} />{absorbed && <div className="locked-absorption"><b>Boosted +{absorbed.sacrificeBoost} OVR</b><span>Absorbed {absorbed.name} · {absorbed.tier} Tier</span></div>}{prep?.decision === 'sacrifice' && <div className="locked-absorption"><b>Sacrificial OC Activated</b><span>{prep.recipientCount} same-verse {prep.recipientCount === 1 ? 'fighter' : 'fighters'} empowered</span></div>}<div className="preparation-waiting"><i>⌛</i><strong>{state.opponentLocked ? 'Opponent locked. Preparing battle...' : 'Waiting for opponent to lock in...'}</strong></div></section></main>
  }
  const selectedAbsorb = state.eligibleSacrifices.find(card => card.matchCharacterId === choice.id)
  const isChampion = oc.ocType === 'champion'; const cannotActivate = !isChampion && state.eligibleSacrifices.length === 0
  const invalidChoice = isChampion ? choice.decision === 'absorb' && !choice.id : choice.decision === 'sacrifice' && cannotActivate
  return <main className="game-page preparation-page"><section className="oc-preparation"><p className="eyebrow">OC Preparation</p><h1>Choose Your Strategy</h1><OcSummary name={oc.name} verse={oc.verseName} type={oc.ocType} overall={oc.baseOverall} power={oc.powerScore} imageUrl={oc.imageUrl} />{error && <p className="online-draft-message" role="alert">{error}</p>}{isChampion ? <ChampionChoices state={state} choice={choice} selectedAbsorb={selectedAbsorb} selectChoice={selectChoice} hover={sounds.playCardHover} /> : <SacrificialChoices state={state} choice={choice} cannotActivate={cannotActivate} selectChoice={selectChoice} hover={sounds.playCardHover} />}<div className="preparation-warning"><i>!</i><p>{isChampion ? 'An absorbed fighter cannot be used in battle this match.' : 'If sacrificed, your OC cannot enter battle this match.'}<br />This decision cannot be changed.</p></div><button className="button button-primary preparation-lock" disabled={pending || invalidChoice} onClick={() => void onLock(choice.decision as 'reserve' | 'absorb' | 'inactive' | 'sacrifice', choice.id)}>{pending ? 'Locking...' : 'Lock Preparation'}</button></section></main>
}

function ChampionChoices({ state, choice, selectedAbsorb, selectChoice, hover }: { state: MatchOcPreparationState; choice: Choice; selectedAbsorb: MatchOcPreparationState['eligibleSacrifices'][number] | undefined; selectChoice: (choice: Choice) => void; hover: () => void }) {
  const oc = state.yourOC!
  return <div className="strategy-grid"><button type="button" aria-pressed={choice.decision === 'reserve'} className={`strategy-card ${choice.decision === 'reserve' ? 'selected' : ''}`} onMouseEnter={hover} onClick={() => selectChoice({ decision: 'reserve', id: null })}><span className="strategy-icon">♕</span><small>Champion</small><h2>Keep as Reserve</h2><p>No absorption. All five canon fighters remain available.</p><strong>Your Champion stays ready.</strong><div className="reserve-visual"><span /><span /><span /><span /><i>✦</i></div></button><section className={`strategy-card sacrifice ${choice.decision === 'absorb' ? 'selected' : ''}`}><span className="strategy-icon">⚔</span><h2>Absorb a Fighter</h2><p>Absorb one same-verse fighter for a temporary OVR boost.</p><strong>One fighter becomes unavailable.</strong>{state.eligibleSacrifices.length === 0 ? <div className="no-sacrifice"><b>No same-verse fighters available.</b><span>Keep your Champion as reserve.</span></div> : <div className="sacrifice-options">{state.eligibleSacrifices.map(card => <button type="button" aria-pressed={choice.id === card.matchCharacterId} key={card.matchCharacterId} className={choice.id === card.matchCharacterId ? 'selected' : ''} onMouseEnter={hover} onClick={() => selectChoice({ decision: 'absorb', id: card.matchCharacterId })}><span><b>{card.name}</b><small>{card.overall} OVR · {card.tier} Tier</small></span><i>→</i><strong>+{card.sacrificeBoost}<small> OVR</small></strong></button>)}</div>}{selectedAbsorb && <div className="absorption-result"><span>{selectedAbsorb.name}</span><b>{oc.baseOverall} → {Math.min(99, oc.baseOverall + selectedAbsorb.sacrificeBoost)} OVR</b></div>}</section></div>
}

function SacrificialChoices({ state, choice, cannotActivate, selectChoice, hover }: { state: MatchOcPreparationState; choice: Choice; cannotActivate: boolean; selectChoice: (choice: Choice) => void; hover: () => void }) {
  return <div className="strategy-grid"><button type="button" aria-pressed={choice.decision === 'reserve'} className={`strategy-card ${choice.decision === 'reserve' ? 'selected' : ''}`} onMouseEnter={hover} onClick={() => selectChoice({ decision: 'reserve', id: null })}><span className="strategy-icon">◇</span><small>Default</small><h2>Keep as Reserve</h2><p>Keep all five canon fighters at their normal match stats.</p><strong>Your OC remains available to fight once.</strong></button><button type="button" disabled={cannotActivate} aria-pressed={choice.decision === 'sacrifice'} className={`strategy-card sacrifice ${choice.decision === 'sacrifice' ? 'selected' : ''}`} onMouseEnter={cannotActivate ? undefined : hover} onClick={() => selectChoice({ decision: 'sacrifice', id: null })}><span className="strategy-icon">✦</span><h2>Sacrifice OC</h2><p>Give up this OC to empower every drafted same-verse fighter.</p><strong>OVR stays unchanged. Battle Power increases.</strong>{cannotActivate ? <div className="no-sacrifice"><b>No Same-Verse Fighters</b><span>This OC cannot empower your current team.</span></div> : <div className="empower-preview">{state.eligibleSacrifices.map(card => <span key={card.matchCharacterId}><b>{card.name}</b><small>{card.powerScore.toLocaleString()} → {card.matchPowerScore?.toLocaleString()} Power (+{card.effectiveBonus?.toLocaleString()})</small></span>)}</div>}</button></div>
}

function OcSummary({ name, verse, type, overall, power, imageUrl }: { name: string; verse: string; type: 'champion' | 'sacrificial' | null; overall: number; power: number; imageUrl: string | null }) { const typeLabel = type === 'champion' ? 'Champion' : type === 'sacrificial' ? 'Sacrificial' : 'Unknown'; return <div className="oc-preparation-summary"><OCImage src={imageUrl} name={name} className="oc-preparation-portrait" /><span><strong>{name}</strong><small>{verse}</small><em className={`oc-type-badge ${type ?? 'unknown'}`}>{typeLabel}</em></span><div><b>{overall} OVR</b><small>{power.toLocaleString()} Power</small></div></div> }
function WaitingState({ title, text }: { title: string; text: string }) { return <section className="oc-preparation waiting"><p className="eyebrow">OC Preparation</p><h1>{title}</h1><div className="preparation-waiting"><i>⌛</i><strong>{text}</strong></div></section> }
